server:
  port: 8081
spring:
  application:
    name: novy-eapc
  datasource:
    password:
    url: jdbc:mysql://127.0.0.1:3306/novy_eapc?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

